### ISSUE TITLE
Process required for a working install on Forge provisioned servers (Digital Ocean)

### ISSUE THREAD

**Issue by KS-Verbosity** [spatie/laravel-pdf#111]
### What happened?

So far it has not been possible to get an application into production as all attempts at a Forge solution have failed. Many attempts have been made and at best the result is the same as what is listed in Discussion 93 - https://github.com/spatie/laravel-pdf/discussions/93
Definitely looking for updated guidance. I will report any success if I find a solution.

### How to reproduce the bug

Move a working Laravel 10 app with the PDF tool installed (from MacOS using Herd Pro). Everything works fine locally, but it has not been possible to get a working install done on a Forge server (Digital Ocean).

### Package Version

1.1

### PHP Version

8.2.15

### Laravel Version

10.45.1

### Which operating systems does with happen with?

Linux

### Notes

Digital Ocean server
/home/forge/.nvm/versions/node/v21.7.1/bin/node
npm updated
Errors such as these are as close as it gets to working:
The command "PATH=$PATH:/usr/local/bin:/opt/homebrew/bin NODE_PATH=`/home/forge/.nvm/versions/node/v21.7.1/bin/node /home/forge/.nvm/versions/node/v21.7.1/bin/npm root -g` /home/forge/.nvm/versions/node/v21.7.1/bin/node '/home/forge/xxx.com/vendor/spatie/browsershot/src/../bin/browser.cjs' ''" failed.

Exit Code: 1(General error)

Error Output:
================
Error: net::ERR_FILE_NOT_FOUND at file:///tmp/106890602-0196505001711765888/index.html
    at navigate (/home/forge/xxx.com/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Frame.js:171:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Deferred.race (/home/forge/xxx.com/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:36:20)
    at async CdpFrame.goto (/home/forge/xxx.com/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Frame.js:137:25)
    at async CdpPage.goto (/home/forge/xxx.com/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:590:20)

**Comment by Janqu** [comment]
# Working solution for me
Maybe it will solve your problem too.

<img width="558" alt="Bildschirmfoto 2024-03-31 um 00 18 32" src="https://github.com/spatie/laravel-pdf/assets/3251532/5c6ec7ba-6eb7-43e3-bf60-19c7342c6434">

# Error Output
My problem with Hetzner Cloud Ubuntu 22.04 and Laravel 11
Development environment is also Herd Pro on MacOS 

   Symfony\Component\Process\Exception\ProcessTimedOutException  The process "PATH=$PATH:/usr/local/bin:/opt/homebrew/bin NODE_PATH=`npm root -g` node 'vendor/spatie/browsershot/src/../bin/browser.cjs' '{"url":"file:\/\/\/tmp\/194482169-0286861001711839596\/index.html","action":"pdf","options":{"path":"invoice.pdf","args":[],"viewport":{"width":800,"height":600},"displayHeaderFooter":false,"printBackground":true}}'" exceeded the timeout of 60 seconds.
   
   [115372:115372:0330/231700.707395:ERROR:zygote_host_impl_linux.cc(100)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

**Comment by kaspernowak** [comment]
Hey @KS-Verbosity, I struggled a lot with getting this to work on my ubuntu server with openlitespeed, but I got it to work eventually, see this: https://github.com/spatie/laravel-pdf/discussions/134#discussioncomment-9309129
